adminUser:
  password: vault:cjxd10-manual-eks-test/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: dgozalo@cloudbees.com
  token: vault:cjxd10-manual-eks-test/pipelineUser:token
  username: dgozalo
prow:
  hmacToken: vault:cjxd10-manual-eks-test/prow:hmacToken
